seml:
  executable: seml/scripts/rdp/eval_without_replacement.py
  conda_environment: group_amplification
  project_root_dir: ../../../../../..
  output_dir: /ceph/hdd/staff/schuchaj/group_amplification_results/neurips24/logs
  name: wor_baseline

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:0
    mem: 4G          # memory
    cpus-per-task: 2  # num cores
    time: 00-00:10     # max time, D-HH:MM
    partition: cpu,cpu_large
    qos: phdcpu

fixed:
  save_dir: /ceph/hdd/staff/schuchaj/group_amplification_results/neurips24/rdp/without_replacement

  alphas:
    space: log
    params:
      start: 0
      stop: 4
      num: 121

  base_mechanism:
    name: randomizedresponse
  
  amplification:
    subsampling_scheme: withoutreplacement
    tight: False
    params:
      dataset_size: 10000
      eval_params:
        use_self_consistency: False
        hoelders_exponent: 2
        tight_base_guarantee: False

grid:
  base_mechanism.params.true_response_prob:
    type: choice
    options:
      - 0.55
      - 0.6
      - 0.7
      - 0.75
      - 0.8
      - 0.9
      - 0.95
  
  amplification.params.batch_size:
    type: choice
    options:
      - 5000
      - 2000
      - 1000
      - 100
      - 10
  
  amplification.params.group_size:
    type: choice
    options:
      - 1
      - 2
      - 4
      - 8
  
  amplification.params.eval_method:
    type: choice
    options:
      #- traditional
      - recursive
      #- gaussian
