seml:
  executable: seml/scripts/adp/eval_poisson.py
  conda_environment: group_amplification
  project_root_dir: ../../../../..
  output_dir: anonymous
  name: poisson_baseline

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:0
    mem: 4G          # memory
    cpus-per-task: 2  # num cores
    time: 00-00:10     # max time, D-HH:MM
    partition: cpu,cpu_large
    qos: phdcpu

fixed:
  save_dir: anonymous

  epsilons:
    space: linear_continuous
    params:
      start: 0
      stop: 4
      num: 121

  base_mechanism:
    name: gaussian
  
  amplification:
    subsampling_scheme: poisson
    tight: True
    params:
      eval_method: bisection
      eval_params:
        pessimistic_estimate: True
        log_mass_truncation_bound: -50

grid:
  base_mechanism.params.standard_deviation:
    type: choice
    options:
      - 0.1
      - 0.2
      - 0.5
      - 1.0
      - 2.0
      - 5.0
  
  amplification.params.subsampling_rate:
    type: choice
    options:
      - 0.5
      - 0.2
      - 0.1
      - 0.01
      - 0.001
  
  amplification.params.group_size:
    type: choice
    options:
      - 1
      - 1
      - 2
      - 2
      - 2
      - 4
      - 4
      - 4
      - 4
      - 4
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
      - 16
    zip_id: group

  amplification.params.insertions:
    type: choice
    options:
      - 0
      - 1
      - 0
      - 1
      - 2
      - 0
      - 1
      - 2
      - 3
      - 4
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
    zip_id: group
